# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8b0a9567407e3ccbe5f881eb68547eb62339f0c87e2e92e6c2e7270aeb524af2113760d438cd9610786dab9e8dbd8ec13115ead6a4fdf8c4e8c40dc9c1bbfcb

test:
  secret_key_base: 9d750e77b5f99e2a475f8b4fda884a496869f1e925bc61aa8b29cbce8f5f456983174f032cab3ea359b7e21071381123ce7990607bc8e7941d3e8a4170e7165c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
